apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: nodejs-build-and-deploy
spec:
  params:
    - name: git-url
      type: string
      description: The git URL for the source code.
    - name: git-revision
      type: string
      description: The git revision.
      default: "master"
  workspaces:
  - name: shared-workspace
  tasks:
  - name: fetch-repository
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: $(params.git-url)
    - name: revision
      value: $(params.git-revision)
  - name: build
    taskRef:
      name: s2i-nodejs
    workspaces:
    - name: source
      workspace: shared-workspace
    params:
    - name: PATH_CONTEXT
      value: "nodejs-helloworld"
    runAfter:
    - fetch-repository
  - name: deploy
    taskRef:
      name: openshift-client
    runAfter:
    - build
    params:
    - name: script
      value: |
        cd nodejs-helloworld
        oc rollout latest nodejs-app

